### PR TITLE
Add 3Speak to users

### PR DESCRIPTION
**Pull request by vaultec81**
[3Speak](https://3speak.co) is planning on utilizing OrbitDB.

### CODE REVIEW

**Comment by aphelionz** [comment]
Cool, how far along is the integration?

**Comment by vaultec81** [comment]
At the moment 3Speak is planning to use orbitdb in one way or another. Most likely going to be user accounts, community video databases, and playlists. There might be more uses, but that hasn't been settled yet. (Right now there is no code to show, hoping to have stuff available soon, ETA 1-2months or sooner)

**Comment by aphelionz** [comment]
Well if you're confident enough to feel it warrants putting on the OrbitDB site, more power to you. Let me know when this is out of draft! We can easily revert this later if something changes

**Comment by vaultec81** [comment]
Will let you know for sure.

**Comment by haadcode** [comment]
Closing as stale.

**Pull request closed without merging**
