### PR TITLE
add link to community chats

### PR DESCRIPTION
**Pull request by tabcat**
this adds a link to the OrbitDB gitter which, from looking at the text, seems like it was in the works anyway.

I made it link to the Lobby channel of OrbitDB as that looked like the best option.

### CODE REVIEW

**Comment by aphelionz** [comment]
I like it! I think we should link to the permaweb discord and the gitter, anywhere the readme badger link

**Comment by tabcat** [comment]
im guessing you want those in the same pr then?

how should I word this, maybe:

OrbitDB has an active developer community. Your best place to find us is on [Gitter](https://gitter.im/orbitdb/Lobby).
We also have communities on [Matrix](https://riot.im/app/#/room/#orbit-db:matrix.org) and [Discord](https://discord.gg/v3RNE3M).

**Comment by aphelionz** [comment]
Yeah, sorry for not being clear. That would be great. The chat is bridged across all three so it's more or less the "same" room

**Review by aphelionz — APPROVED** [review]

**Comment by RichardLitt** [comment]
Thanks, @tabcat :)

**Pull request merged**
